std_msgs/Header header

yhs_can_interfaces/CtrlFb     ctrl_fb
yhs_can_interfaces/IoFb       io_fb

yhs_can_interfaces/LrWheelFb   lr_wheel_fb
yhs_can_interfaces/RrWheelFb   rr_wheel_fb

yhs_can_interfaces/LfWheelFb   lf_wheel_fb
yhs_can_interfaces/RfWheelFb   rf_wheel_fb

yhs_can_interfaces/FrontAngleFb      front_angle_fb 
yhs_can_interfaces/RearAngleFb      rear_angle_fb 

yhs_can_interfaces/BmsFlagFb  bms_flag_fb 
yhs_can_interfaces/BmsFb      bms_fb 
